name: freeze_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:   
    sdk: flutter
  web_socket_channel: ^3.0.3
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  intl: ^0.20.2
  flutter_local_notifications: ^17.2.3


dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
